package com.shinowit.model;

import java.io.Serializable;

public class SexInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sex_info.sex_id
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    private String sexId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sex_info.sex_type
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    private String sexType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sex_info
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sex_info.sex_id
     *
     * @return the value of sex_info.sex_id
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    public String getSexId() {
        return sexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sex_info.sex_id
     *
     * @param sexId the value for sex_info.sex_id
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    public void setSexId(String sexId) {
        this.sexId = sexId == null ? null : sexId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sex_info.sex_type
     *
     * @return the value of sex_info.sex_type
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    public String getSexType() {
        return sexType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sex_info.sex_type
     *
     * @param sexType the value for sex_info.sex_type
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    public void setSexType(String sexType) {
        this.sexType = sexType == null ? null : sexType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_info
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SexInfo other = (SexInfo) that;
        return (this.getSexId() == null ? other.getSexId() == null : this.getSexId().equals(other.getSexId()))
            && (this.getSexType() == null ? other.getSexType() == null : this.getSexType().equals(other.getSexType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_info
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSexId() == null) ? 0 : getSexId().hashCode());
        result = prime * result + ((getSexType() == null) ? 0 : getSexType().hashCode());
        return result;
    }
}