package com.shinowit.model;

import java.io.Serializable;

public class StuInfo implements Serializable {

    private SexInfo sexInfo;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_info.stu_id
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    private String stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_info.sex_id
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    private String sexId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_info.stu_name
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stu_info
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_info.stu_id
     *
     * @return the value of stu_info.stu_id
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    public String getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_info.stu_id
     *
     * @param stuId the value for stu_info.stu_id
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    public void setStuId(String stuId) {
        this.stuId = stuId == null ? null : stuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_info.sex_id
     *
     * @return the value of stu_info.sex_id
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    public String getSexId() {
        return sexId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_info.sex_id
     *
     * @param sexId the value for stu_info.sex_id
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    public void setSexId(String sexId) {
        this.sexId = sexId == null ? null : sexId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_info.stu_name
     *
     * @return the value of stu_info.stu_name
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_info.stu_name
     *
     * @param stuName the value for stu_info.stu_name
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_info
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    public SexInfo getSexInfo() {
        return sexInfo;
    }

    public void setSexInfo(SexInfo sexInfo) {
        this.sexInfo = sexInfo;
    }


}