package com.shinowit.dao.mapper;

import com.shinowit.model.SexInfo;
import com.shinowit.model.SexInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SexInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_info
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    int countByExample(SexInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_info
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    int deleteByExample(SexInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_info
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    int deleteByPrimaryKey(String sexId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_info
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    int insert(SexInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_info
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    int insertSelective(SexInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_info
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    List<SexInfo> selectByExample(SexInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_info
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    SexInfo selectByPrimaryKey(String sexId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_info
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    int updateByExampleSelective(@Param("record") SexInfo record, @Param("example") SexInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_info
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    int updateByExample(@Param("record") SexInfo record, @Param("example") SexInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_info
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    int updateByPrimaryKeySelective(SexInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sex_info
     *
     * @mbggenerated Tue Dec 23 18:21:10 CST 2014
     */
    int updateByPrimaryKey(SexInfo record);

    List<SexInfo> selectPage(SexInfoExample example);

    String selectMaxPrimaryKeyValue();
}